### ISSUE TITLE
Unnatural use of pagination

### ISSUE THREAD

**Issue by hanaral** [candiedoperation/marquer#3]
Page dots are generally used with galleries and other types of non-layered menus (like the elementary onboarding window), so it's a bit odd to use it for a menu that's one layer deeper than the intro screen (also having the dots there makes it look like there is an another separate menu to the right)
Keep up the good work!

**Comment by candiedoperation** [comment]
@hanaral, Requesting you to have a look at the linked pull request. I've implemented suggestions related to the carousel indicators.

**Comment by hanaral** [comment]
@candiedoperation I think lines do look better, but if you really want to show page indicators in a multi-layered menu, I can only suggest page numbers to more explicitly imply it isn't a gallery view (lines still don't specifically show that they are steps).

**Comment by hanaral** [comment]
Ok, so I've properly had the chance to test the app now, and think this issue should be re-opened;
The the pagination makes the views seem unrelated - being able to swipe through a destructive action rather than being guided is dangerous and may result in user wiping disks accidentally

Here are the issues I see to be caused by the unnecessary pagination:
- You can move between views without doing anything
- There is no guiding the user through actions (remember, the elementary installer forces the user to read each page, as the actions are all destructive)
- The user can swipe in and out of an error message, making it seem meaningless

**The simplest solution IMO is to just not use the swipe-y cool page changing, for the same reason elementary's installer doesn't.
If you want to keep a page indicator, put a badge somewhere on the screen with the number of the step (don't let users use it as the mode of navigation though)**
